Repository buefy/buefy, pull requests merged in 2024-01, with the labels that each got.

#3964 Update CHANGELOG from v0.9.27 to v0.9.28 with issue links
  CHANGELOG.md
Labels: docs, improvement

#3968 Chore: Add information on and the link to ntohq/buefy-next to README.md
  README.md
Labels: docs, improvement

#3863 feature(Autocomplete): add @active event whenever dropdown is active
  docs/pages/components/autocomplete/api/autocomplete.js
  src/components/autocomplete/Autocomplete.spec.js
  src/components/autocomplete/Autocomplete.vue
Labels: improvement

#3862 Expose isActiveDetailRow method in table component column slot props
  src/components/table/Table.vue
  src/components/table/TableColumn.spec.js
Labels: feature request

#3988 chore(docs): update table column docs for default slot
  docs/pages/components/table/api/table.js
Labels: docs

#3991 Clear event listeners and timers before component unmounts
  docs/components/TheNavbar.vue
  docs/templates/Documentation.vue
  src/components/numberinput/Numberinput.vue
  src/components/sidebar/Sidebar.vue
  src/components/slider/SliderThumb.vue
Labels: bug, improvement

#3989 Docs: update CHANGELOG on v0.9.28
  CHANGELOG.md
Labels: docs

#4006 docs: updated the documentation page's codepen
  docs/pages/Documentation.vue
Labels: docs
