Repository buefy/buefy, pull requests merged in 2025-07, with the labels that each got.

#4048 Fix: correct defaultDatepickerYearsRange value in docs
  docs/pages/components/datepicker/api/datepicker.js
  docs/pages/installation/api/constructor-options.js
Labels: Buefy Vue2

#4139 FIX various bugs on Autocomplete component
  packages/buefy/src/components/autocomplete/Autocomplete.spec.ts
  packages/buefy/src/components/autocomplete/Autocomplete.vue
Labels: enhancement

#4161 Update Discord Links
  README.md
  packages/buefy/README.md
  packages/docs/src/components/TheNavbar.vue
Labels: Buefy Vue3, documentation

#4156 fix(Snackbar): export SnackbarOpenParams type
  packages/buefy/src/components/snackbar/index.ts
Labels: enhancement

#4166 Update Social Links
  packages/docs/src/assets/scss/_variables.scss
  packages/docs/src/components/TheFooter.vue
  packages/docs/src/components/TheNavbar.vue
  packages/docs/src/pages/Expo.vue
Labels: Buefy Vue3, enhancement

#4170 Migrate to StackBlitz⚡
  package-lock.json
  package.json
  packages/docs/src/components/CodepenEdit.vue
  packages/docs/src/components/Example.vue
  packages/docs/src/components/StackBlitzEdit.vue
  packages/docs/src/data/stackblitz.ts
  packages/docs/src/utils/stackBlitz.ts
Labels: enhancement, documentation

#4176 Fix ImproveThis Link
  packages/docs/src/components/ImproveThis.vue
Labels: enhancement

#4173 Bump to v1.0.2
  package-lock.json
  package.json
  packages/buefy/package.json
  packages/docs/package.json
Labels: enhancement
